collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7800486
  brandStrength: 0.270079
  rhythmicContrast: 0.9814246
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.1417098
typography_spectrum: 0.7599356
layout_spectrum: 0.4731471
name: Tsuyoshi
