layout_spectrum: 0.8095196
typography_spectrum: 0.1149711
color:
  saturation: 0.7800486
  lightness: 0.1417098
  brandStrength: 0.270079
  rhythmicContrast: 0.9814246
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Tsuyoshi
